=== samarjit/servershell/src/main/java/map/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="screen"/>
        <xs:element ref="panels"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="screen">
	<xs:complexType>
		<xs:sequence >
			<xs:element ref="htmltemplate" />
			<xs:element ref="includedjsp" />
			<xs:element ref="callbackclass" />
			<xs:element ref="scripts" />
			<xs:element ref="stylesheets" />
			<xs:element name="sessionvars" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element ref="crud" />
			<xs:element ref="dm" />
			<xs:element ref="bl" />
			<xs:element ref="anyprocs" />
			<xs:element ref="commands" />
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string" />
	</xs:complexType>
  </xs:element>
  <xs:element name="htmltemplate" type="xs:string" />
  <xs:element name="includedjsp" type="xs:string" >
     
  </xs:element>
  <xs:element name="callbackclass" type="xs:string"/>
  <xs:element name="scripts">
    <xs:complexType >
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="scriptinclude"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="text"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="scriptinclude" type="xs:string"/>
  <xs:element name="stylesheets">
    <xs:complexType>
      <xs:choice  maxOccurs="unbounded" minOccurs="0"> 
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="styleinclude"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="text"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="styleinclude" type="xs:string"/>
  <xs:element name="panels">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="panel"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="panel">
    <xs:complexType >
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="button"/>
        <xs:element ref="fields"/>
        <xs:element name="testscriptlet" type="xs:string"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="button">
		<xs:complexType>
			<xs:simpleContent>
				<xs:restriction base="xs:anyType">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1" />
	
						</xs:restriction>
					</xs:simpleType>
					<xs:attribute name="forid" use="required" type="xs:string" />
					<xs:attribute name="onclick" />
					<xs:attribute name="id" use="optional" />
					<xs:attribute name="type" use="required" />
					<xs:attribute name="replace" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="modify" />
								<xs:enumeration value="append" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
	
				</xs:restriction>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
  <xs:element name="crud">
    <xs:complexType>
       
        <xs:sequence >
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="jsonrpc"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="selectonload"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="sqlselect"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="savefieldids"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="sqlinsert"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="sqldelete"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="sqlselectcount"/>
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="sqlupdate"/>
          
        </xs:sequence>
     
    </xs:complexType>
  </xs:element>
  <xs:element name="jsonrpc">
    <xs:complexType mixed="true">
      <xs:sequence>
      	 <xs:element minOccurs="0" maxOccurs="1" ref="countquery"/>
         <xs:element minOccurs="0" maxOccurs="1" ref="error"/>
         <xs:element minOccurs="0" maxOccurs="1" ref="message"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="outstack" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="savefieldids">
    <xs:complexType/>
  </xs:element>
  <xs:element name="selectonload">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="countquery"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="error"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="message"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
      <xs:attribute name="outstack" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="countquery">
    <xs:complexType mixed="true">
      <xs:attribute name="pagesize" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sqlselect">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="countquery"/>
      	<xs:element minOccurs="0" maxOccurs="unbounded" ref="error"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="message"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="outstack" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sqlinsert" >
      <xs:complexType mixed="true"> 
        <xs:sequence>
      	<xs:element minOccurs="0" maxOccurs="unbounded" ref="error"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="message"/>
	   </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="outstack" use="required" type="xs:string"/>
      </xs:complexType>
  </xs:element>
  <xs:element name="sqldelete"  >
      <xs:complexType mixed="true"> 
        <xs:sequence>
      	<xs:element minOccurs="0" maxOccurs="unbounded" ref="error"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="message"/>
	   </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="outstack" use="required" type="xs:string"/>
      </xs:complexType>
  </xs:element>
  <xs:element name="sqlselectcount">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="refselectid" use="required" type="xs:string"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="sqlupdate" >
      <xs:complexType mixed="true"> 
        <xs:sequence>
      	<xs:element minOccurs="0" maxOccurs="unbounded" ref="error"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="message"/>
	   </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="outstack" use="required" type="xs:string"/>
      </xs:complexType>
  </xs:element>
  <xs:element name="dm">
    <xs:complexType  >
       <xs:sequence>
       	<xs:element name="txnproc" minOccurs="0" maxOccurs="unbounded" >
       		<xs:complexType mixed="true">
       		 <xs:attribute name="id" type="xs:string"></xs:attribute>
       		  <xs:attribute name="outstack" type="xs:string"></xs:attribute>
       		</xs:complexType>
       	</xs:element>
       </xs:sequence>
       
    </xs:complexType> 
  </xs:element>
  <xs:element name="bl">
    <xs:complexType >
       <xs:sequence>
       	<xs:element name="buslogic" minOccurs="0" maxOccurs="unbounded" >
       		<xs:complexType mixed="true">
       		 <xs:attribute name="id" type="xs:string"></xs:attribute>	
       		 <xs:attribute name="method" type="xs:string"></xs:attribute>	
       		</xs:complexType>
       	</xs:element>
       </xs:sequence>
       <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType> 
  </xs:element>
  <xs:element name="anyprocs">
  	 <xs:complexType>
  	 	<xs:sequence >
  	 	<xs:element name="proc" maxOccurs="unbounded" minOccurs="0">     		 
	        <xs:complexType mixed="true">
	          <xs:attribute name="id" type="xs:string"></xs:attribute>
	           <xs:attribute name="outstack" type="xs:string"></xs:attribute>
	        </xs:complexType>	
       	</xs:element>
       	</xs:sequence>
  	  </xs:complexType>
  </xs:element>
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   <xs:element name="error">
    <xs:complexType>
      <xs:attribute name="message" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="message">
    <xs:complexType>
      <xs:attribute name="message" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="commands">
  	<xs:complexType>
  		<xs:sequence>
  			<xs:element name="cmd" minOccurs="0"
  				maxOccurs="unbounded">
  				<xs:complexType>
  					<xs:attribute name="instack" use="required"
  						type="xs:string" />
  					<xs:attribute name="name" use="required"
  						type="xs:string" />
  					<xs:attribute name="opt" use="required"
  						type="xs:string" />
  					<xs:attribute name="resultScrName" use="optional"
  						type="xs:string" />
  					<xs:attribute name="result" use="required" />
  				</xs:complexType>
  			</xs:element>
  			<!-- this is bulkcmd -->
  			<xs:element name="bulkcmd" minOccurs="0" maxOccurs="unbounded">
			<xs:annotation>
			      <xs:documentation>Tooltip: bulkcmd will get executed once per request</xs:documentation>
			     </xs:annotation>
  				<xs:complexType>
  					<xs:attribute name="name" use="required"
  						type="xs:string" />
  					<xs:attribute name="opt" use="required"
  						type="xs:string" />
  					<xs:attribute name="result" use="required" />
  					<xs:attribute name="resultScrName" use="optional" />
  				</xs:complexType>
  			</xs:element>
  			<!-- this is onload -->
  			<xs:element name="onload" minOccurs="0" maxOccurs="unbounded">
			<xs:annotation>
			      <xs:documentation>Tooltip: onload will get executed once per page load, or whenever decorator interceptor is called- common.action or subclass of common.action</xs:documentation>
			     </xs:annotation>
  				<xs:complexType>
  					<xs:attribute name="opt" use="required"
  						type="xs:string" />
  				    <xs:attribute name="result" use="required" />
  				</xs:complexType>
  			</xs:element>
  		</xs:sequence>
  	</xs:complexType>
  </xs:element>
  
  
  <xs:element name="field">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded"> 
        <xs:element ref="compositefield"/>
        <xs:element ref="customfield"/>
        <xs:element ref="div"/>
        <xs:element ref="input"/>
        <xs:element ref="select"/>
        <xs:element ref="sometype"/>
        <xs:element ref="displayfield"/>
        <xs:element ref="validationfld"/>
        <xs:element ref="label" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="compositefield">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datafield"/>
        <xs:element maxOccurs="unbounded" ref="displayfield"/>
        <xs:element ref="text"/>
        <xs:element ref="rule"/>
        <xs:element ref="validation"/>
        <xs:element ref="query"/>
      </xs:sequence>
      <xs:attribute name="class" use="required"/>
      <xs:attribute name="column"  />
      <xs:attribute name="dbcolsize"  />
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="mask"  />
      <xs:attribute name="replace" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required"/>
      <xs:attribute name="validationattr" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datafield">
    <xs:complexType>
      <xs:attribute name="column"   type="xs:string"/>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="displayfield">
    <xs:complexType>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="customfield">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="text"/>
        <xs:element minOccurs="0" ref="rule"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="validation"/>
          <xs:element ref="query"/>
        </xs:sequence>
      </xs:sequence>
      <xs:attribute name="class"/>
      <xs:attribute name="column" type="xs:string"/>
      <xs:attribute name="dbcolsize"/>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="mask"/>
      <xs:attribute name="replace" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="validationattr"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="div">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="xpath"/>
        <xs:element ref="rule"/>
        <xs:element minOccurs="0" ref="validation"/>
        <xs:element ref="query"/>
      </xs:sequence>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute ref="replace" use="required"/>
    </xs:complexType>
  </xs:element>
   <xs:element name="label">
    <xs:complexType>
      <xs:attribute name="forname" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:string"/>
      <xs:attribute name="key" use="required" type="xs:string"/>
      <xs:attribute ref="replace" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="xpath">
    <xs:complexType mixed="true">
      <xs:attribute name="position" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="input">
    <xs:complexType>
      <xs:sequence>
          <xs:element ref="rule" minOccurs="0"/>
          <xs:element ref="query" minOccurs="0"/>
          <xs:element ref="validation" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="class"  />
      <xs:attribute name="column"  type="xs:string"/>
      <xs:attribute name="dbcolsize"  />
      <xs:attribute name="dbdatatype" type="xs:string"/>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="hidden"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="label"/>
      <xs:attribute name="mandatory"/>
      <xs:attribute name="mask"  />
      <xs:attribute name="name" use="required" type="xs:string"/>
      <xs:attribute name="primarykey" type="xs:string"/>
      <xs:attribute ref="replace" use="required"  />
      <xs:attribute name="type" use="required"  >
          <xs:simpleType>
         	<xs:restriction  base="xs:string" >
         		 <xs:minLength value="2"></xs:minLength>
         	</xs:restriction>
         </xs:simpleType>
       </xs:attribute>  
      
      <xs:attribute name="validationattr"/>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="validationfld">
    <xs:complexType>
      <xs:sequence>
          <xs:element ref="rule" minOccurs="0"/>
          <xs:element ref="validation" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="column" use="required" type="xs:string"/>
      <xs:attribute name="dbcolsize" use="required" />
      <xs:attribute name="dbdatatype" use="required" type="xs:string"/>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="id"  type="xs:string"/>
      <xs:attribute name="mandatory" use="required" />
      <xs:attribute name="mask"  />
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:attribute name="replace">
  <xs:simpleType >
    <xs:restriction  base="xs:string">
         		<xs:enumeration value="modify" />
         		<xs:enumeration value="append" />
    </xs:restriction>
  </xs:simpleType>
  </xs:attribute> 
  <xs:element name="select">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="text"/>
        <xs:element minOccurs="0" ref="rule"/>
        <xs:element minOccurs="0" ref="validation"/>
        <xs:element minOccurs="0" ref="query"/>
      </xs:sequence>
      <xs:attribute name="class" use="optional"/>
      <xs:attribute name="column" use="optional" type="xs:string"/>
      <xs:attribute name="dbcolsize" use="optional"/>
      <xs:attribute name="dbdatatype" type="xs:string"/>
      <xs:attribute name="forid" use="required" type="xs:string"/>
      <xs:attribute name="hidden"/>
      <xs:attribute name="id" use="required" type="xs:string"/>
      <xs:attribute name="label"/>
      <xs:attribute name="mandatory"/>
      <xs:attribute name="mask" use="optional"/>
      <xs:attribute name="name"  use="required" type="xs:string"/>
      <xs:attribute use="required" ref="replace"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="validationattr"/>
      <xs:attribute name="value" use="optional"/>
      <xs:attribute name="key" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sometype">
    <xs:complexType>
      <xs:attribute name="dbdatatype"   type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="text" type="xs:string"/>
  <xs:element name="rule" type="xs:string"/>
  <xs:element name="validation">
    <xs:complexType>
    
    </xs:complexType> 
  </xs:element>
  <xs:element name="query">
    <xs:complexType mixed="true">
      <xs:attribute name="type" >
       <xs:simpleType>
       	 <xs:restriction base="xs:string">
       	 	  <xs:enumeration value="SQL" />
              <xs:enumeration value="QUERYID" />
       	 </xs:restriction>
       </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="stackid" type="xs:string"/>
    </xs:complexType>
  </xs:element>
 
</xs:schema>

=== samarjit/servershell/src/main/java/map/jsptest/PassionUserTemp.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config.xsd">
  <screen name="PassionUserTemp">
    <htmltemplate></htmltemplate>
    <includedjsp></includedjsp>
    <callbackclass></callbackclass>
    <scripts>
      <scriptinclude></scriptinclude>
    </scripts>
    <stylesheets>
      <styleinclude></styleinclude>
    </stylesheets>
    <sessionvars>sessionvars</sessionvars>
    <crud>
	   <jsonrpc outstack="formonload" id="onloadqry1">SELECT CARD_NO "cardno",ID_VALUE "idvalue",ID_TYPE "idtype",ACTION_FLAG "actionflag",VALID_CARD "validcard",ALREADY_REGISTERED "alreadyregistered",REGISTRATION_COMPLETED "registrationcompleted",INPUT_FILE_NAME "inputfilename",RETURN_FILE_CREATED "returnfilecreated",ERROR_CODE "errorcode",FILE_PROCESSED_FLAG "fileprocessedflag",NATIONALITY "nationality",ERROR_MSG "errormsg" FROM PASSION_USER_TEMP 
			<countquery pagesize="10">select count('x') from PASSION_USER_TEMP </countquery>
	   </jsonrpc>
       <jsonrpc outstack="formpagination" id="gridonload">SELECT CARD_NO "cardno",ID_VALUE "idvalue",ID_TYPE "idtype",ACTION_FLAG "actionflag",VALID_CARD "validcard",ALREADY_REGISTERED "alreadyregistered",REGISTRATION_COMPLETED "registrationcompleted",INPUT_FILE_NAME "inputfilename",RETURN_FILE_CREATED "returnfilecreated",ERROR_CODE "errorcode",FILE_PROCESSED_FLAG "fileprocessedflag",NATIONALITY "nationality",ERROR_MSG "errormsg" FROM PASSION_USER_TEMP 
			<countquery pagesize="10">select count('x') from PASSION_USER_TEMP </countquery>
	   </jsonrpc>
<!--GRID INSERTS (check out which alias is required-->
      <sqlinsert id="frmgridadd" outstack="inst">insert into PASSION_USER_TEMP( CARD_NO, ID_VALUE, ID_TYPE, ACTION_FLAG, VALID_CARD, ALREADY_REGISTERED, REGISTRATION_COMPLETED, INPUT_FILE_NAME, RETURN_FILE_CREATED, ERROR_CODE, FILE_PROCESSED_FLAG, NATIONALITY, ERROR_MSG) values ( #inp.form1[0].CARD_NO, #inp.form1[0].ID_VALUE, #inp.form1[0].ID_TYPE, #inp.form1[0].ACTION_FLAG, #inp.form1[0].VALID_CARD, #inp.form1[0].ALREADY_REGISTERED, #inp.form1[0].REGISTRATION_COMPLETED, #inp.form1[0].INPUT_FILE_NAME, #inp.form1[0].RETURN_FILE_CREATED, #inp.form1[0].ERROR_CODE, #inp.form1[0].FILE_PROCESSED_FLAG, #inp.form1[0].NATIONALITY, #inp.form1[0].ERROR_MSG )</sqlinsert>
      <sqlinsert id="gridadd" outstack="inst">insert into PASSION_USER_TEMP( CARD_NO, ID_VALUE, ID_TYPE, ACTION_FLAG, VALID_CARD, ALREADY_REGISTERED, REGISTRATION_COMPLETED, INPUT_FILE_NAME, RETURN_FILE_CREATED, ERROR_CODE, FILE_PROCESSED_FLAG, NATIONALITY, ERROR_MSG) values ( #inp.form1[0].CARD_NO, #inp.form1[0].ID_VALUE, #inp.form1[0].ID_TYPE, #inp.form1[0].ACTION_FLAG, #inp.form1[0].VALID_CARD, #inp.form1[0].ALREADY_REGISTERED, #inp.form1[0].REGISTRATION_COMPLETED, #inp.form1[0].INPUT_FILE_NAME, #inp.form1[0].RETURN_FILE_CREATED, #inp.form1[0].ERROR_CODE, #inp.form1[0].FILE_PROCESSED_FLAG, #inp.form1[0].NATIONALITY, #inp.form1[0].ERROR_MSG )</sqlinsert>
      <sqldelete id="frmgriddel" outstack="delt">delete from PASSION_USER_TEMP WHERE CARD_NO = #inp.form1[0].CARD_NO|STRING</sqldelete>
      <sqldelete id="griddel" outstack="delt">delete from PASSION_USER_TEMP WHERE CARD_NO = #inp.form1[0].id|STRING</sqldelete>
      <sqlupdate id="frmgridedit" outstack="updt">update PASSION_USER_TEMP set  ID_VALUE = #inp.form1[0].ID_VALUE, ID_TYPE = #inp.form1[0].ID_TYPE, ACTION_FLAG = #inp.form1[0].ACTION_FLAG, VALID_CARD = #inp.form1[0].VALID_CARD, ALREADY_REGISTERED = #inp.form1[0].ALREADY_REGISTERED, REGISTRATION_COMPLETED = #inp.form1[0].REGISTRATION_COMPLETED, INPUT_FILE_NAME = #inp.form1[0].INPUT_FILE_NAME, RETURN_FILE_CREATED = #inp.form1[0].RETURN_FILE_CREATED, ERROR_CODE = #inp.form1[0].ERROR_CODE, FILE_PROCESSED_FLAG = #inp.form1[0].FILE_PROCESSED_FLAG, NATIONALITY = #inp.form1[0].NATIONALITY, ERROR_MSG = #inp.form1[0].ERROR_MSG WHERE CARD_NO=#inp.form1[0].CARD_NO</sqlupdate>
      <sqlupdate id="gridedit" outstack="updt">update PASSION_USER_TEMP set  ID_VALUE = #inp.form1[0].ID_VALUE, ID_TYPE = #inp.form1[0].ID_TYPE, ACTION_FLAG = #inp.form1[0].ACTION_FLAG, VALID_CARD = #inp.form1[0].VALID_CARD, ALREADY_REGISTERED = #inp.form1[0].ALREADY_REGISTERED, REGISTRATION_COMPLETED = #inp.form1[0].REGISTRATION_COMPLETED, INPUT_FILE_NAME = #inp.form1[0].INPUT_FILE_NAME, RETURN_FILE_CREATED = #inp.form1[0].RETURN_FILE_CREATED, ERROR_CODE = #inp.form1[0].ERROR_CODE, FILE_PROCESSED_FLAG = #inp.form1[0].FILE_PROCESSED_FLAG, NATIONALITY = #inp.form1[0].NATIONALITY, ERROR_MSG = #inp.form1[0].ERROR_MSG WHERE CARD_NO=#inp.form1[0].id|STRING</sqlupdate>
    </crud>
    <dm>
      <txnproc id="" outstack=""/>
    </dm>
    <bl id="">
      <buslogic id="" method=""/>
    </bl>
    <anyprocs>
      <proc id="" outstack=""/>
    </anyprocs>
    <commands>
      <cmd instack="" name="" opt=""  result="" />
      <bulkcmd name="fromViewTransition" opt="" result="ajax" resultScrName="PassionUserTemp" />
      <bulkcmd name="frmgridadd" opt="sqlinsert:frmgridadd" result="ajax" resultScrName="PassionUserTemp"/>
      <bulkcmd name="frmgridedit" opt="sqlupdate:frmgridedit" result="ajax"/>
      <bulkcmd name="frmgriddel" opt="sqldelete:frmgriddel" result="ajax"/>
      <bulkcmd name="griddel" opt="sqldelete:griddel" result="ajax"/>
      <bulkcmd name="gridedit" opt="sqlupdate:gridedit" result="ajax"/>
      <bulkcmd name="gridadd" opt="sqlinsert:gridadd" result="ajax"/>
      <bulkcmd name="gridonload" opt="jsonrpc:gridonload" result="ajax"/>
      <onload opt="jsonrpc:onloadqry1" result="/jsptest/PassionUserTemp.jsp"/>
    </commands>
  </screen>
  <panels>
    <panel id="">
       <fields>
          <field>
          	<validationfld dbcolsize="16" name="cardno" column="CARD_NO" mandatory="yes" forid="cardno" dbdatatype="STRING" />
          	<validationfld dbcolsize="25" name="idvalue" column="ID_VALUE" mandatory="yes" forid="idvalue" dbdatatype="STRING" />
          	<validationfld dbcolsize="10" name="idtype" column="ID_TYPE" mandatory="yes" forid="idtype" dbdatatype="STRING" />
          	<validationfld dbcolsize="20" name="actionflag" column="ACTION_FLAG" mandatory="yes" forid="actionflag" dbdatatype="STRING" />
          	<validationfld dbcolsize="1" name="validcard" column="VALID_CARD" mandatory="yes" forid="validcard" dbdatatype="STRING" />
          	<validationfld dbcolsize="1" name="alreadyregistered" column="ALREADY_REGISTERED" mandatory="yes" forid="alreadyregistered" dbdatatype="STRING" />
          	<validationfld dbcolsize="1" name="registrationcompleted" column="REGISTRATION_COMPLETED" mandatory="yes" forid="registrationcompleted" dbdatatype="STRING" />
          	<validationfld dbcolsize="100" name="inputfilename" column="INPUT_FILE_NAME" mandatory="yes" forid="inputfilename" dbdatatype="STRING" />
          	<validationfld dbcolsize="1" name="returnfilecreated" column="RETURN_FILE_CREATED" mandatory="yes" forid="returnfilecreated" dbdatatype="STRING" />
          	<validationfld dbcolsize="10" name="errorcode" column="ERROR_CODE" mandatory="yes" forid="errorcode" dbdatatype="STRING" />
          	<validationfld dbcolsize="1" name="fileprocessedflag" column="FILE_PROCESSED_FLAG" mandatory="yes" forid="fileprocessedflag" dbdatatype="STRING" />
          	<validationfld dbcolsize="5" name="nationality" column="NATIONALITY" mandatory="yes" forid="nationality" dbdatatype="STRING" />
          	<validationfld dbcolsize="30" name="errormsg" column="ERROR_MSG" mandatory="yes" forid="errormsg" dbdatatype="STRING" />

          	<label replace="modify" key="cardno" value="Card No" forname="cardno"/>
          	<label replace="modify" key="idvalue" value="Id Value" forname="idvalue"/>
          	<label replace="modify" key="idtype" value="Id Type" forname="idtype"/>
          	<label replace="modify" key="actionflag" value="Action Flag" forname="actionflag"/>
          	<label replace="modify" key="validcard" value="Valid Card" forname="validcard"/>
          	<label replace="modify" key="alreadyregistered" value="Already Registered" forname="alreadyregistered"/>
          	<label replace="modify" key="registrationcompleted" value="Registration Completed" forname="registrationcompleted"/>
          	<label replace="modify" key="inputfilename" value="Input File Name" forname="inputfilename"/>
          	<label replace="modify" key="returnfilecreated" value="Return File Created" forname="returnfilecreated"/>
          	<label replace="modify" key="errorcode" value="Error Code" forname="errorcode"/>
          	<label replace="modify" key="fileprocessedflag" value="File Processed Flag" forname="fileprocessedflag"/>
          	<label replace="modify" key="nationality" value="Nationality" forname="nationality"/>
          	<label replace="modify" key="errormsg" value="Error Msg" forname="errormsg"/>

          </field>
       </fields>
      <button forid="" id="" onclick="" replace="modify" type="">button</button>
    </panel>
  </panels>
</root>
